### ISSUE TITLE
(feature request) allow specifying `cache_directory` for `CacheManager`

### ISSUE THREAD

**Issue by whacked** [OpenGov/py_cache_manager#10]
Have you thought about adding `cache_directory` as a second argument to `cacher.get_cache_manager` to specify the `cache_directory` for `CacheManager`?

If you have, what's the rationale for disallowing it?

If you haven't, this proposal just lets you use something other than `tempfile.gettempdir()` in `CacheManager`'s init. I can create a PR, it will be probably 4 or 5 lines of change and will have no impact on existing code.

The current alternative is to directly set `cache_directory` right after calling `cache.get_cache_manager()`

**Comment by MSeal** [comment]
This feature makes a lot of sense, I think it was just an oversight of the initial design. Thanks for making a PR for it.

**Comment by whacked** [comment]
awesome, thanks!
