### ISSUE TITLE
Ease strict requirements

### ISSUE THREAD

**Issue by K377U** [OpenGov/py_cache_manager#14]
Currently the requirements are very strict, would it be possible to ease them a little?

```
psutil==2.1.0
six==1.10.0
future==0.16.0
```

to

```
psutil>=2.1.0
six>=1.10.0
future>=0.16.0
```
?

**Comment by MSeal** [comment]
That seems reasonable; I'll look into getting a version published with that change.

**Comment by MSeal** [comment]
Running into some travis issues with psutil timeouts -- can't reproduce it locally for https://github.com/OpenGov/py_cache_manager/pull/15/files. Might take a little extra time playing with variations to make python 3.3-3.5 happy on travis.

**Comment by MSeal** [comment]
@K377U Sorry for the long delay, there were some annoying race conditions revealed in the tests by upgrading psutils that took a bit to fix on my spare time. v2.0.8 should have the requested eased requirements.
